version: "3.8"
services:
  db:
    image: mysql:8.0
    container_name: mysql_clinic
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_USER: user_clinic
      MYSQL_PASSWORD: Thien?1010
    ports:
      - "3307:3306"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend-service:
    container_name: backend_clinic
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - default
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/clinic?useSSL=true&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: user_clinic
      SPRING_DATASOURCE_PASSWORD: Thien?1010
    depends_on:
      - db
