spring:
  datasource:
#    url: jdbc:mysql://192.168.1.109:3336/clinic?useSSL=false&serverTimezone=UTC
#    url: jdbc:mysql://localhost:3306/clinic?useSSL=false&serverTimezone=UTC
    url: mysql://root:FYTIKsCkvWwzBKTbxihqgcOLgdKijmQg@trolley.proxy.rlwy.net:48689/railway
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
#    password: Thien?1010
    password: FYTIKsCkvWwzBKTbxihqgcOLgdKijmQg
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      format_sql: truesa
api:
  prefix: api/clinic
jwt:
  expiration: 2592000    # 30 days = 30 * 24 * 60 * 60 = 2592000
  secretKey: JyTrVJHstjDzFa/ad82sI2oWgHLausH1pYf7U5hm5DM=

servlet:
  multipart:
    max-file-size: 10MB
    max-request-size: 10MB