server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://db:3306/clinic?useSSL=true&serverTimezone=UTC
#    url: jdbc:mysql://localhost:3306/clinic?useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: user_clinic
#    username: root
    password: Thien?1010
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

api:
  prefix: api/clinic

jwt:
  expiration: 2592000    # 30 days = 30 * 24 * 60 * 60 = 2592000
  secretKey: JyTrVJHstjDzFa/ad82sI2oWgHLausH1pYf7U5hm5DM=

servlet:
  multipart:
    max-file-size: 10MB
    max-request-size: 10MB

openapi:
  service:
    api-docs: backend-service
    server: http://localhost:${server.port}/${api.prefix}
    title: Backend service
    version: 1.0.0